name: alpha2_countries
version: 2.0.0
description: ISO 3166-1 alpha-2 country codes.
author: Maido Käära <maido@getchange.com>
homepage: https://github.com/ChangeFinance/alpha2_countries

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10

environment:
  sdk: '>=2.12.0 <3.0.0'
