name: alpha2_countries
version: 1.0.2
description: ISO 3166-1 alpha-2 country codes.
author: Maido Käära <maido@getchange.com>
homepage: https://github.com/ChangeFinance/alpha2_countries

dependencies:
  resource: ^2.1.5

dev_dependencies:
  mockito: any
  test: any

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'
