name: alpha2_countries
version: 2.0.0
description: ISO 3166-1 alpha-2 country codes.
author: Maido Käära <maido@getchange.com>
homepage: https://github.com/ChangeFinance/alpha2_countries

dev_dependencies:
  mockito: any
  test: ^1.16.5

environment:
  sdk: '>=2.12.0 <3.0.0'
